tags:
- name: users
  description: users API
- name: payments
  description: payments API

paths:
  # [GET] users
  /api/users:
    get:
      tags:
      - users
      summary: Find All Users
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'
  /api/users/signup:
    post:
      tags:
      - users
      summary: Add User
      parameters:
      - name: body
        in: body
        description: user Data
        required: true
        schema:
          $ref: '#/definitions/users'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  /api/users/login:
    post:
      tags:
      - users
      summary: Login User
      parameters:
      - name: body
        in: body
        description: user Data
        required: true
        schema:
          $ref: '#/definitions/users'
      responses:
        200:
          description: 'Login Successful'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'       

  /api/users/{id}:
    get:
      tags:
      - users
      summary: Find User By Id
      parameters:
      - name: id
        in: path
        description: User Id
        required: true
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

    put:
      tags:
      - users
      summary: Update User By Id
      parameters:
      - name: id
        in: path
        description: user Id
        required: true
      - name: body
        in: body
        description: user Data
        required: true
        schema:
          $ref: '#/definitions/users'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

    delete:
      tags:
      - users
      summary: Delete User By Id
      parameters:
      - name: id
        in: path
        description: user Id
        required: true
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  /api/categories:
    post:
      tags:
      - Category
      summary: Create Category
      parameters:
      - name: body
        in: body
        description: Category Data
        required: true
        schema:
          $ref: '#/definitions/category'
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'
    get:
      tags:
      - Category
      summary: Find All Categories
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'
  /api/categories/{id}:
    put:
      tags:
      - Category
      summary: Update Category By Id
      parameters:
      - name: id
        in: path
        description: Category Id
        required: true
      - name: body
        in: body
        description: Category Data
        required: true
        schema:
          $ref: '#/definitions/category'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  /api/customers:
    post:
      tags:
      - customers
      summary: Add Customer
      parameters:
      - name: body
        in: body
        description: customer Data
        required: true
        schema:
          $ref: '#/definitions/customer'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'
    get:
      tags:
      - customers
      summary: Find All Customers
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'
  # [POST] payments
  /api/bills/createpayment:
    post:
      tags:
      - payments
      summary: Add Payment
      parameters:
      - name: body
        in: body
        description: payment Data
        required: true
        schema:
          $ref: '#/definitions/payments'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'
  /api/bills/getpayments:
    get:
      tags:
      - payments
      summary: Find All Payments
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'
  /api/bill/updatepayment/{id}:
    put:
      tags:
      - payments
      summary: Update Payment By Id
      parameters:
      - name: id
        in: path
        description: payment Id
        required: true
        type: string
      - name: body
        in: body
        description: payment Data
        required: true
        schema:
          $ref: '#/definitions/payments'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'
  /api/bill/getpayment/{id}:
    get:
      tags:
      - payments
      summary: Find Payment By Id
      parameters:
      - name: id
        in: path
        description: payment Id
        required: true
        type: string
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'
  /api/bill/{id}:
    delete:
      tags:
      - payments
      summary: Delete Payment By Id
      parameters:
      - name: id
        in: path
        description: payment Id
        required: true
        type: string
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'
  /api/cashManagement/createcash:
    post:
      tags:
      - cashManagement
      summary: Add Cash
      parameters:
      - name: body
        in: body
        description: cash Data
        required: true
        schema:
          $ref: '#/definitions/cashManagement'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'
  /api/cashManagement/getcash:
    get:
      tags:
      - cashManagement
      summary: Find All Cash
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'
  /api/cashManagement/updatecash/{id}:
    put:
      tags:
      - cashManagement
      summary: Update Cash By Id
      parameters:
      - name: id
        in: path
        description: cash Id
        required: true
        type: string
      - name: body
        in: body
        description: cash Data
        required: true
        schema:
          $ref: '#/definitions/cashManagement'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'
  /api/cashManagement/deletecash/{id}:
    delete:
      tags:
      - cashManagement
      summary: Delete Cash By Id
      parameters:
      - name: id
        in: path
        description: cash Id
        required: true
        type: string
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'
definitions:
  users:
    type: object
    required:
      - firstName
      - email
      - password
    properties:
      firstName:
        type: string
        description: user First Name
      lastName:
        type: string
        description: user Last Name
      email:
        type: string
        description: user Email
      password:
        type: string
        description: user Password

  payments:
    type: object
    required:
      - products
      - quantity
      - rate
      - total
    properties:
      products:
        type: string
        description: Products
      quantity:
        type: number
        description: Quantity
      rate:
        type: number
        description: Rate
      total:
        type: number
        description: Total

  category:
    type: object
    required:
      - name
    properties:
      name:
        type: string
        description: Category Name
  
  customer:
    type: object
    required:
      - name
      - mobile
    properties:
      name:
        type: string
        description: Customer Name
      mobile:
        type: string
        description: Customer mobile number
  cashManagement:
    type: object
    required:
      - amount
      - type
    properties:
      amount:
        type: string
        description: Cash
      notes:
        type: string
        description: Status
      type:
        type: string
        description: Type
schemes:
- https
- http
